name: Redeliver Failed GitHub Webhooks

on:
  push:
    branches:
      - develop

jobs:
  redeliver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment variables
      run: |
        export OWNER="Fiserv"
        export REPO="Testing-repo"
        export TOKEN="Bearer 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"
        export API="https://api.github.com/repos/$OWNER/$REPO"

    - name: Get list of hook IDs
      run: |
        hooks_response=$(curl -s -H "Authorization: Bearer $TOKEN" "$API/hooks")
        echo "Response from API: $hooks_response"
        hook_ids=$(echo "$hooks_response" | jq -r '.[].id')
        echo "Hook IDs: $hook_ids"
