name: Webhook Failure Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check webhook status
        run: |
          WEBHOOK_STATUS=$(curl -X POST -H "Authorization: Bearer $TEST_GITHUB_AUTH_TOKEN" -H "Content-Type: application/json" https://api.github.com/repos/Testing-repo/actions/workflows/your-workflow.yml/dispatches -d '{"ref":"develop"}')
          echo "Webhook Status: $WEBHOOK_STATUS"
