name: Webhook Failure Workflow

on:
  push:
    branches:
      - develop

jobs:
  check_webhook_status:
    runs-on: ubuntu-latest

    steps:
    - name: Check Webhook Status
      id: webhook_status
      run: |
        echo "The webhook status is: ${{ github.event.webhook_url_status }}"
