name: Webhook Failure Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check webhook status
        run: |
          curl -X GET "https://dev-developer.fiserv.com/api/github-push"

