name: Webhook Failure Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check webhook status
        run: |
          curl -X GET ${{ github.event.webhook_url }}

      - name: Only run if the webhook failed
        if: ${{ !stdout }}
        run: |
          echo "The webhook failed!"
