name: Re-trigger failed webhook payload
on:
  repository_dispatch:
    types: [failed_webhook]

jobs:
  retrigger:
    runs-on: ubuntu-latest
    steps:
      - name: Get webhook payload
        id: get-payload
        uses: actions/github-script@v3
        with:
          script: |
            const payload = JSON.parse(github.event.client_payload);
            const webhookUrl = payload.url;
            const webhookSecret = payload.secret;

            // Re-trigger the webhook
            const headers = {
              'Authorization': `Bearer ${webhookSecret}`,
            };
            fetch(webhookUrl, {
              method: 'POST',
              headers,
            });

      - name: Log payload
        run: |
          echo "Payload: ${{ steps.get-payload.outputs.payload }}"
